from django.urls import path

from erp.views import (
    BranchListView,
    LoginView,
    LogoutView,
    MeView,
    ProfileView,
    TenantTokenRefreshView,
)
from erp.views_inventory import (
    BrandDetailView,
    BrandListCreateView,
    ClassificationDetailView,
    ClassificationListCreateView,
    ColorDetailView,
    ColorListCreateView,
    InventorySettingsView,
    ProductDetailView,
    ProductListCreateView,
    ProductBarcodePreviewView,
    ProductNextBarcodeView,
    ProductVariantSyncView,
    StockAdditionActionView,
    StockAdditionListCreateView,
    StockAdditionOptionsView,
    StockDisbursementActionView,
    StockDisbursementListCreateView,
    StockDisbursementOptionsView,
    StockScrapActionView,
    StockScrapListCreateView,
    StockTransferActionView,
    StockTransferListCreateView,
    StockTransferOptionsView,
    ProductSectionDetailView,
    ProductSectionListCreateView,
    SeasonDetailView,
    SeasonListCreateView,
    SizeDetailView,
    SizeListCreateView,
    StockBalanceListView,
    SupplierDetailView,
    SupplierListCreateView,
    WarehouseDetailView,
    WarehouseListCreateView,
)
from erp.views_suppliers import (
    SupplierGroupDetailView,
    SupplierGroupListCreateView,
    SupplierMetaView,
    SupplierPaymentActionView,
    SupplierPaymentListCreateView,
    SupplierTypeDetailView,
    SupplierCategoryDetailView,
    SupplierCategoryListCreateView,
    SupplierDepartmentDetailView,
    SupplierDepartmentListCreateView,
    SupplierTypeListCreateView,
    SupplierWeeklyInventoryMarkSentView,
    SupplierWeeklyInventoryReportDetailView,
    SupplierWeeklyInventoryReportListView,
    SupplierWeeklyInventoryRunDailyView,
)
from erp.views_customers import (
    CustomerCheckDuplicateView,
    CustomerDetailView,
    CustomerPurchaseItemsView,
    CustomerGroupDashboardView,
    CustomerGroupDetailView,
    CustomerGroupListCreateView,
    CustomerListCreateView,
    CustomerMetaView,
    CustomerNextCodeView,
    CustomerTypeDetailView,
    CustomerTypeListCreateView,
)
from erp.views_consignment import (
    ConsignmentCustomerBalanceView,
    ConsignmentCustomerCountSheetView,
    ConsignmentDashboardView,
    ConsignmentMovementApproveView,
    ConsignmentMovementCancelView,
    ConsignmentMovementDetailView,
    ConsignmentMovementListCreateView,
    ConsignmentRealtimeSalesView,
    ConsignmentReportsView,
)
from erp.views_receivables import (
    CustomerArrearsView,
    CustomerAccountStatementView,
    CustomerAutoRemindersView,
    CustomerCrmDashboardView,
    CustomerFollowUpView,
    CustomerReminderView,
    InstallmentFollowUpBulkUpdateView,
    InstallmentFollowUpListNumberView,
    InstallmentFollowUpListView,
    InstallmentFollowUpOptionsView,
    InstallmentFollowUpPenaltiesView,
    InstallmentFollowUpRemindersView,
    InstallmentFollowUpSavedListsView,
    InstallmentContractDetailView,
    InstallmentContractListCreateView,
    InstallmentCollectionView,
    InstallmentLineActionView,
    InstallmentMergeView,
    InstallmentPlanListView,
    InstallmentPlanDetailView,
    InstallmentPlanPreviewView,
    InstallmentReportsView,
)
from erp.views_inventory_extended import (
    BarcodePrintView,
    CompositeProductDetailView,
    CompositeProductListCreateView,
    OkazionNoticeApplyView,
    OkazionNoticeDetailView,
    OkazionNoticeListView,
    OkazionNoticePreviewView,
    StoreOfferNoticeApplyView,
    StoreOfferNoticeDetailView,
    StoreOfferNoticeListView,
    StoreOfferNoticePreviewView,
    PriceAdjustmentListCreateView,
    PriceAdjustmentPreviewView,
    StockCountActionView,
    StockCountDetailView,
    StockCountListCreateView,
    StockValuationView,
    SupplierAccountLedgerView,
    GeneralItemMovementReportView,
    SupplierGroupInventoryReportView,
    ScanOrderListCreateView,
    ScanOrderDetailView,
    ScanOrderActionView,
    ScanOrderLookupView,
    ScanOrderEmployeeLookupView,
)
from erp.views_pos import (
    PosContextView,
    PosCustomerOpenDocsView,
    PosCustomerReviewListView,
    PosDeliveryOrderDetailView,
    PosDeliveryOrdersView,
    PosSellerListView,
    PosSellerLookupView,
    PosExchangeView,
    PosProductSearchView,
    PosSaleListCreateView,
)
from erp.views_sales import (
    CustomerReservationActionView,
    CustomerReservationListCreateView,
    CustomerReservationLookupView,
    SaleReturnListCreateView,
    SalesQuotationActionView,
    SalesQuotationListCreateView,
    SalesQuotationLookupView,
    SalesInvoiceDetailView,
    SalesInvoiceListCreateView,
    SellerPerformanceReportView,
    TaxInvoiceListView,
)
from erp.views_purchases import (
    PurchaseInvoiceCancelView,
    PurchaseInvoiceDetailView,
    PurchaseInvoiceListCreateView,
    PurchaseInvoiceReceiveView,
    PurchaseProductsLookupView,
    PurchaseQuickCreateProductView,
    PurchaseReturnListCreateView,
)
from erp.views_purchase_orders import (
    CreateOrdersFromReorderView,
    PurchaseOrderDetailView,
    PurchaseOrderListView,
    PurchaseOrderReceiveView,
    ReorderAlertsView,
)
from erp.views_hr_payroll import (
    AllowanceAssignmentDetailView,
    AllowanceAssignmentListCreateView,
    AllowanceItemDetailView,
    AllowanceItemListCreateView,
    AttendanceImportView,
    AttendanceListCreateView,
    BonusItemDetailView,
    BonusItemListCreateView,
    BonusListCreateView,
    CommissionRecordListCreateView,
    EmployeeCommissionReportView,
    DeductionItemDetailView,
    DeductionItemListCreateView,
    DeductionListCreateView,
    EmployeeAdvanceListCreateView,
    EmployeeLeaveListCreateView,
    LeaveTypeDetailView,
    LeaveTypeListCreateView,
    OfficialHolidayDetailView,
    OfficialHolidayListCreateView,
    PaymentTypeDetailView,
    PaymentTypeListCreateView,
    PayrollPaymentListCreateView,
    PayrollSheetView,
    PayrollStatementDetailView,
    PayrollStatementListCreateView,
)
from erp.views_hr import (
    DepartmentDetailView,
    DepartmentListCreateView,
    EmployeeAllowanceCreateView,
    EmployeeAllowanceDeleteView,
    EmployeeDataDetailView,
    EmployeeDataListView,
    EmployeeDetailView,
    EmployeeGroupDetailView,
    EmployeeGroupListCreateView,
    EmployeeLimitsView,
    EmployeeListCreateView,
    EmployeeSalaryIncreaseCreateView,
    EmployeeSalaryIncreaseDeleteView,
    HrSectionDetailView,
    HrSectionListCreateView,
    JobTitleDetailView,
    JobTitleListCreateView,
    PermissionsSchemaView,
    WorkShiftDetailView,
    WorkShiftListCreateView,
)
from erp.views_accounting import (
    CostCenterListView,
    ExpenseTypeDetailView,
    ExpenseTypeListCreateView,
    ExpenseTypeNextCodeView,
    GlAccountListView,
)
from erp.views_accounting_vouchers import (
    CashShiftActionView,
    CashShiftActiveUsersView,
    CashShiftDailyReportView,
    CashShiftDetailView,
    EnterpriseCashDashboardView,
    CashShiftListView,
    CashShiftMyOpenView,
    CashShiftOpenView,
    CashShiftPosGateView,
    ExpenseVoucherActionView,
    ExpenseVoucherDetailView,
    ExpenseVoucherListCreateView,
    TreasuryListView,
)
from erp.views_accounting_reports import (
    BalanceSheetView,
    GeneralLedgerView,
    IncomeStatementView,
    JournalEntryActionView,
    JournalEntryDetailView,
    JournalEntryListCreateView,
    ReportExportView,
    TrialBalanceView,
)
from erp.views_accounting_core import (
    ChartGlAccountsLookupView,
    ChartNextCodeView,
    ChartOfAccountsDetailView,
    ChartOfAccountsListCreateView,
    CurrencyConvertView,
    CurrencyDetailView,
    CurrencyListCreateView,
    FixedAssetBulkDepreciateView,
    FixedAssetDepreciateView,
    FixedAssetListCreateView,
)
from erp.views_banking import (
    BankAccountDetailView,
    BankAccountListCreateView,
    BankAccountMovementListCreateView,
    BankAccountMovementPostView,
    BankDetailView,
    BankListCreateView,
    ChequeAlertsView,
    ChequeDetailView,
    ChequeListCreateView,
    ChequeCancelView,
    ChequeDeliverView,
    ChequePayView,
    ChequeRejectView,
    ChequeReturnView,
    PaymentMethodsDashboardView,
    CardAccountDetailView,
    CardAccountListCreateView,
    CardNetworkDetailView,
    CardNetworkListCreateView,
    CardTransactionListCreateView,
    CardTransactionRejectView,
    CardTransactionSettleView,
    ChannelTransferListCreateView,
    BankingStatementView,
    EWalletAccountDetailView,
    EWalletAccountListCreateView,
    EWalletMovementListCreateView,
    EWalletMovementPostView,
    EWalletProviderDetailView,
    EWalletProviderListCreateView,
)
from erp.views_accounting_extended import (
    PendingShiftActionView,
    PendingShiftsView,
    ShiftHandoverActionView,
    ShiftHandoverDetailView,
    ShiftHandoverListCreateView,
    TreasuryAuditLogView,
    TreasuryBalanceListView,
    TreasuryMovementActionView,
    TreasuryMovementListCreateView,
)

urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/refresh/", TenantTokenRefreshView.as_view(), name="auth-refresh"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/profile/", ProfileView.as_view(), name="auth-profile"),
    path("organization/branches/", BranchListView.as_view(), name="branches"),
    path("organization/warehouses/", WarehouseListCreateView.as_view(), name="warehouses"),
    path("organization/warehouses/<uuid:pk>/", WarehouseDetailView.as_view(), name="warehouse-detail"),
    path("organization/seasons/", SeasonListCreateView.as_view(), name="seasons"),
    path("organization/seasons/<uuid:pk>/", SeasonDetailView.as_view(), name="season-detail"),
    path("inventory/sections/", ProductSectionListCreateView.as_view(), name="product-sections"),
    path("inventory/sections/<uuid:pk>/", ProductSectionDetailView.as_view(), name="product-section-detail"),
    path("inventory/brands/", BrandListCreateView.as_view(), name="brands"),
    path("inventory/brands/<uuid:pk>/", BrandDetailView.as_view(), name="brand-detail"),
    path("inventory/classifications/", ClassificationListCreateView.as_view(), name="classifications"),
    path("inventory/classifications/<uuid:pk>/", ClassificationDetailView.as_view(), name="classification-detail"),
    path("inventory/sizes/", SizeListCreateView.as_view(), name="sizes"),
    path("inventory/sizes/<uuid:pk>/", SizeDetailView.as_view(), name="size-detail"),
    path("inventory/colors/", ColorListCreateView.as_view(), name="colors"),
    path("inventory/colors/<uuid:pk>/", ColorDetailView.as_view(), name="color-detail"),
    path("inventory/products/", ProductListCreateView.as_view(), name="products"),
    path("inventory/products/next-barcode/", ProductNextBarcodeView.as_view(), name="product-next-barcode"),
    path(
        "inventory/products/barcode-preview/",
        ProductBarcodePreviewView.as_view(),
        name="product-barcode-preview",
    ),
    path("inventory/inventory-settings/", InventorySettingsView.as_view(), name="inventory-settings"),
    path("inventory/products/<uuid:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("inventory/products/<uuid:pk>/variants/", ProductVariantSyncView.as_view(), name="product-variants"),
    path("inventory/stock-balances/", StockBalanceListView.as_view(), name="stock-balances"),
    path(
        "inventory/stock-transfers/options/",
        StockTransferOptionsView.as_view(),
        name="stock-transfer-options",
    ),
    path("inventory/stock-transfers/", StockTransferListCreateView.as_view(), name="stock-transfers"),
    path(
        "inventory/stock-transfers/<uuid:pk>/<str:action>/",
        StockTransferActionView.as_view(),
        name="stock-transfer-action",
    ),
    path("inventory/stock-scrap/", StockScrapListCreateView.as_view(), name="stock-scrap"),
    path(
        "inventory/stock-scrap/<uuid:pk>/<str:action>/",
        StockScrapActionView.as_view(),
        name="stock-scrap-action",
    ),
    path(
        "inventory/stock-disbursements/options/",
        StockDisbursementOptionsView.as_view(),
        name="stock-disbursement-options",
    ),
    path(
        "inventory/stock-disbursements/",
        StockDisbursementListCreateView.as_view(),
        name="stock-disbursements",
    ),
    path(
        "inventory/stock-disbursements/<uuid:pk>/<str:action>/",
        StockDisbursementActionView.as_view(),
        name="stock-disbursement-action",
    ),
    path(
        "inventory/stock-additions/options/",
        StockAdditionOptionsView.as_view(),
        name="stock-addition-options",
    ),
    path(
        "inventory/stock-additions/",
        StockAdditionListCreateView.as_view(),
        name="stock-additions",
    ),
    path(
        "inventory/stock-additions/<uuid:pk>/<str:action>/",
        StockAdditionActionView.as_view(),
        name="stock-addition-action",
    ),
    path("inventory/stock-valuation/", StockValuationView.as_view(), name="stock-valuation"),
    path(
        "inventory/reports/supplier-group/",
        SupplierGroupInventoryReportView.as_view(),
        name="supplier-group-inventory-report",
    ),
    path(
        "inventory/reports/general-item-movement/",
        GeneralItemMovementReportView.as_view(),
        name="general-item-movement-report",
    ),
    path(
        "inventory/supplier-accounts/",
        SupplierAccountLedgerView.as_view(),
        name="supplier-accounts",
    ),
    path("inventory/scan-orders/", ScanOrderListCreateView.as_view(), name="scan-orders"),
    path("inventory/scan-orders/lookup/", ScanOrderLookupView.as_view(), name="scan-orders-lookup"),
    path(
        "inventory/scan-orders/employee/",
        ScanOrderEmployeeLookupView.as_view(),
        name="scan-orders-employee",
    ),
    path("inventory/scan-orders/<uuid:pk>/", ScanOrderDetailView.as_view(), name="scan-order-detail"),
    path(
        "inventory/scan-orders/<uuid:pk>/<str:action>/",
        ScanOrderActionView.as_view(),
        name="scan-order-action",
    ),
    path("inventory/stock-count/", StockCountListCreateView.as_view(), name="stock-count"),
    path(
        "inventory/stock-count/<uuid:pk>/",
        StockCountDetailView.as_view(),
        name="stock-count-detail",
    ),
    path(
        "inventory/stock-count/<uuid:pk>/<str:action>/",
        StockCountActionView.as_view(),
        name="stock-count-action",
    ),
    path(
        "inventory/composite-products/",
        CompositeProductListCreateView.as_view(),
        name="composite-products",
    ),
    path(
        "inventory/composite-products/<uuid:pk>/",
        CompositeProductDetailView.as_view(),
        name="composite-product-detail",
    ),
    path(
        "inventory/price-adjustments/",
        PriceAdjustmentListCreateView.as_view(),
        name="price-adjustments",
    ),
    path(
        "inventory/price-adjustments/preview/",
        PriceAdjustmentPreviewView.as_view(),
        name="price-adjustments-preview",
    ),
    path(
        "inventory/okazion-notice/preview/",
        OkazionNoticePreviewView.as_view(),
        name="okazion-notice-preview",
    ),
    path(
        "inventory/okazion-notice/apply/",
        OkazionNoticeApplyView.as_view(),
        name="okazion-notice-apply",
    ),
    path(
        "inventory/okazion-notices/",
        OkazionNoticeListView.as_view(),
        name="okazion-notices-list",
    ),
    path(
        "inventory/okazion-notices/<uuid:pk>/",
        OkazionNoticeDetailView.as_view(),
        name="okazion-notice-detail",
    ),
    path(
        "inventory/store-offer-notice/preview/",
        StoreOfferNoticePreviewView.as_view(),
        name="store-offer-notice-preview",
    ),
    path(
        "inventory/store-offer-notice/apply/",
        StoreOfferNoticeApplyView.as_view(),
        name="store-offer-notice-apply",
    ),
    path(
        "inventory/store-offer-notices/",
        StoreOfferNoticeListView.as_view(),
        name="store-offer-notices-list",
    ),
    path(
        "inventory/store-offer-notices/<uuid:pk>/",
        StoreOfferNoticeDetailView.as_view(),
        name="store-offer-notice-detail",
    ),
    path("inventory/barcode-labels/", BarcodePrintView.as_view(), name="barcode-labels"),
    path("inventory/suppliers/meta/", SupplierMetaView.as_view(), name="supplier-meta"),
    path("inventory/supplier-types/", SupplierTypeListCreateView.as_view(), name="supplier-types"),
    path("inventory/supplier-types/<uuid:pk>/", SupplierTypeDetailView.as_view(), name="supplier-type-detail"),
    path("inventory/supplier-groups/", SupplierGroupListCreateView.as_view(), name="supplier-groups"),
    path("inventory/supplier-groups/<uuid:pk>/", SupplierGroupDetailView.as_view(), name="supplier-group-detail"),
    path("inventory/supplier-categories/", SupplierCategoryListCreateView.as_view(), name="supplier-categories"),
    path("inventory/supplier-categories/<uuid:pk>/", SupplierCategoryDetailView.as_view(), name="supplier-category-detail"),
    path("inventory/supplier-departments/", SupplierDepartmentListCreateView.as_view(), name="supplier-departments"),
    path("inventory/supplier-departments/<uuid:pk>/", SupplierDepartmentDetailView.as_view(), name="supplier-department-detail"),
    path("inventory/supplier-payments/", SupplierPaymentListCreateView.as_view(), name="supplier-payments"),
    path(
        "inventory/supplier-payments/<uuid:pk>/<str:action>/",
        SupplierPaymentActionView.as_view(),
        name="supplier-payment-action",
    ),
    path("inventory/suppliers/", SupplierListCreateView.as_view(), name="suppliers"),
    path("inventory/suppliers/<uuid:pk>/", SupplierDetailView.as_view(), name="supplier-detail"),
    path(
        "inventory/supplier-weekly-reports/",
        SupplierWeeklyInventoryReportListView.as_view(),
        name="supplier-weekly-reports",
    ),
    path(
        "inventory/supplier-weekly-reports/run-daily/",
        SupplierWeeklyInventoryRunDailyView.as_view(),
        name="supplier-weekly-reports-run-daily",
    ),
    path(
        "inventory/supplier-weekly-reports/<uuid:pk>/",
        SupplierWeeklyInventoryReportDetailView.as_view(),
        name="supplier-weekly-report-detail",
    ),
    path(
        "inventory/supplier-weekly-reports/<uuid:pk>/mark-sent/",
        SupplierWeeklyInventoryMarkSentView.as_view(),
        name="supplier-weekly-report-mark-sent",
    ),
    path("inventory/customers/meta/", CustomerMetaView.as_view(), name="customers-meta"),
    path("inventory/customer-types/", CustomerTypeListCreateView.as_view(), name="customer-types"),
    path(
        "inventory/customer-types/<uuid:pk>/",
        CustomerTypeDetailView.as_view(),
        name="customer-type-detail",
    ),
    path(
        "inventory/customer-groups/dashboard/",
        CustomerGroupDashboardView.as_view(),
        name="customer-groups-dashboard",
    ),
    path("inventory/customer-groups/", CustomerGroupListCreateView.as_view(), name="customer-groups"),
    path(
        "inventory/customer-groups/<uuid:pk>/",
        CustomerGroupDetailView.as_view(),
        name="customer-group-detail",
    ),
    path("inventory/customers/", CustomerListCreateView.as_view(), name="customers"),
    path(
        "inventory/customers/check-duplicate/",
        CustomerCheckDuplicateView.as_view(),
        name="customers-check-duplicate",
    ),
    path(
        "inventory/customers/next-code/",
        CustomerNextCodeView.as_view(),
        name="customers-next-code",
    ),
    path(
        "inventory/customers/<uuid:pk>/purchase-items/",
        CustomerPurchaseItemsView.as_view(),
        name="customer-purchase-items",
    ),
    path("inventory/customers/<uuid:pk>/", CustomerDetailView.as_view(), name="customer-detail"),
    path(
        "inventory/customers/crm-dashboard/",
        CustomerCrmDashboardView.as_view(),
        name="customers-crm-dashboard",
    ),
    path(
        "inventory/customers/arrears/",
        CustomerArrearsView.as_view(),
        name="customers-arrears",
    ),
    path(
        "inventory/installment-follow-up/options/",
        InstallmentFollowUpOptionsView.as_view(),
        name="installment-follow-up-options",
    ),
    path(
        "inventory/installment-follow-up/",
        InstallmentFollowUpListView.as_view(),
        name="installment-follow-up-list",
    ),
    path(
        "inventory/installment-follow-up/bulk-update/",
        InstallmentFollowUpBulkUpdateView.as_view(),
        name="installment-follow-up-bulk-update",
    ),
    path(
        "inventory/installment-follow-up/list-number/",
        InstallmentFollowUpListNumberView.as_view(),
        name="installment-follow-up-list-number",
    ),
    path(
        "inventory/installment-follow-up/saved-lists/",
        InstallmentFollowUpSavedListsView.as_view(),
        name="installment-follow-up-saved-lists",
    ),
    path(
        "inventory/installment-follow-up/penalties/",
        InstallmentFollowUpPenaltiesView.as_view(),
        name="installment-follow-up-penalties",
    ),
    path(
        "inventory/installment-follow-up/reminders/",
        InstallmentFollowUpRemindersView.as_view(),
        name="installment-follow-up-reminders",
    ),
    path(
        "inventory/customers/account-statement/",
        CustomerAccountStatementView.as_view(),
        name="customer-account-statement",
    ),
    path(
        "inventory/customers/follow-ups/",
        CustomerFollowUpView.as_view(),
        name="customers-follow-ups",
    ),
    path(
        "inventory/customers/reminders/",
        CustomerReminderView.as_view(),
        name="customers-reminders",
    ),
    path(
        "inventory/customers/reminders/auto-run/",
        CustomerAutoRemindersView.as_view(),
        name="customers-reminders-auto",
    ),
    path(
        "inventory/installment-plans/",
        InstallmentPlanListView.as_view(),
        name="installment-plans",
    ),
    path(
        "inventory/installment-plans/preview/",
        InstallmentPlanPreviewView.as_view(),
        name="installment-plans-preview",
    ),
    path(
        "inventory/installment-plans/<uuid:pk>/",
        InstallmentPlanDetailView.as_view(),
        name="installment-plan-detail",
    ),
    path(
        "inventory/installment-contracts/",
        InstallmentContractListCreateView.as_view(),
        name="installment-contracts",
    ),
    path(
        "inventory/installment-contracts/reports/",
        InstallmentReportsView.as_view(),
        name="installment-reports",
    ),
    path(
        "inventory/installment-collection/",
        InstallmentCollectionView.as_view(),
        name="installment-collection",
    ),
    path(
        "inventory/installment-contracts/<uuid:pk>/",
        InstallmentContractDetailView.as_view(),
        name="installment-contract-detail",
    ),
    path(
        "inventory/installment-lines/<uuid:pk>/",
        InstallmentLineActionView.as_view(),
        name="installment-line-action",
    ),
    path(
        "inventory/installment-lines/merge/",
        InstallmentMergeView.as_view(),
        name="installment-lines-merge",
    ),
    path(
        "inventory/consignment/dashboard/",
        ConsignmentDashboardView.as_view(),
        name="consignment-dashboard",
    ),
    path(
        "inventory/consignment/movements/",
        ConsignmentMovementListCreateView.as_view(),
        name="consignment-movements",
    ),
    path(
        "inventory/consignment/movements/<uuid:pk>/",
        ConsignmentMovementDetailView.as_view(),
        name="consignment-movement-detail",
    ),
    path(
        "inventory/consignment/movements/<uuid:pk>/approve/",
        ConsignmentMovementApproveView.as_view(),
        name="consignment-movement-approve",
    ),
    path(
        "inventory/consignment/movements/<uuid:pk>/cancel/",
        ConsignmentMovementCancelView.as_view(),
        name="consignment-movement-cancel",
    ),
    path(
        "inventory/consignment/customers/<uuid:customer_id>/balance/",
        ConsignmentCustomerBalanceView.as_view(),
        name="consignment-customer-balance",
    ),
    path(
        "inventory/consignment/customers/<uuid:customer_id>/count-sheet/",
        ConsignmentCustomerCountSheetView.as_view(),
        name="consignment-customer-count-sheet",
    ),
    path(
        "inventory/consignment/customers/<uuid:customer_id>/realtime-sales/",
        ConsignmentRealtimeSalesView.as_view(),
        name="consignment-realtime-sales",
    ),
    path(
        "inventory/consignment/reports/",
        ConsignmentReportsView.as_view(),
        name="consignment-reports",
    ),
    path("hr/permissions-schema/", PermissionsSchemaView.as_view(), name="hr-permissions-schema"),
    path("hr/departments/", DepartmentListCreateView.as_view(), name="hr-departments"),
    path("hr/departments/<uuid:pk>/", DepartmentDetailView.as_view(), name="hr-department-detail"),
    path("hr/sections/", HrSectionListCreateView.as_view(), name="hr-sections"),
    path("hr/sections/<uuid:pk>/", HrSectionDetailView.as_view(), name="hr-section-detail"),
    path("hr/work-shifts/", WorkShiftListCreateView.as_view(), name="hr-work-shifts"),
    path("hr/work-shifts/<uuid:pk>/", WorkShiftDetailView.as_view(), name="hr-work-shift-detail"),
    path("hr/employees/", EmployeeListCreateView.as_view(), name="hr-employees"),
    path("hr/employees/limits/", EmployeeLimitsView.as_view(), name="hr-employee-limits"),
    path("hr/employees/<uuid:pk>/", EmployeeDetailView.as_view(), name="hr-employee-detail"),
    path("hr/job-titles/", JobTitleListCreateView.as_view(), name="hr-job-titles"),
    path("hr/job-titles/<uuid:pk>/", JobTitleDetailView.as_view(), name="hr-job-title-detail"),
    path("hr/employee-groups/", EmployeeGroupListCreateView.as_view(), name="hr-employee-groups"),
    path(
        "hr/employee-groups/<uuid:pk>/",
        EmployeeGroupDetailView.as_view(),
        name="hr-employee-group-detail",
    ),
    path("hr/employee-data/", EmployeeDataListView.as_view(), name="hr-employee-data"),
    path(
        "hr/employee-data/<uuid:pk>/",
        EmployeeDataDetailView.as_view(),
        name="hr-employee-data-detail",
    ),
    path(
        "hr/employee-data/<uuid:pk>/allowances/",
        EmployeeAllowanceCreateView.as_view(),
        name="hr-employee-allowance-create",
    ),
    path(
        "hr/employee-data/<uuid:pk>/allowances/<uuid:allowance_id>/",
        EmployeeAllowanceDeleteView.as_view(),
        name="hr-employee-allowance-delete",
    ),
    path(
        "hr/employee-data/<uuid:pk>/salary-increases/",
        EmployeeSalaryIncreaseCreateView.as_view(),
        name="hr-employee-increase-create",
    ),
    path(
        "hr/employee-data/<uuid:pk>/salary-increases/<uuid:increase_id>/",
        EmployeeSalaryIncreaseDeleteView.as_view(),
        name="hr-employee-increase-delete",
    ),
    path("hr/bonus-items/", BonusItemListCreateView.as_view(), name="hr-bonus-items"),
    path("hr/bonus-items/<uuid:pk>/", BonusItemDetailView.as_view(), name="hr-bonus-item-detail"),
    path("hr/bonuses/", BonusListCreateView.as_view(), name="hr-bonuses"),
    path("hr/deduction-items/", DeductionItemListCreateView.as_view(), name="hr-deduction-items"),
    path(
        "hr/deduction-items/<uuid:pk>/",
        DeductionItemDetailView.as_view(),
        name="hr-deduction-item-detail",
    ),
    path("hr/deductions/", DeductionListCreateView.as_view(), name="hr-deductions"),
    path("hr/allowance-items/", AllowanceItemListCreateView.as_view(), name="hr-allowance-items"),
    path(
        "hr/allowance-items/<uuid:pk>/",
        AllowanceItemDetailView.as_view(),
        name="hr-allowance-item-detail",
    ),
    path("hr/allowances/", AllowanceAssignmentListCreateView.as_view(), name="hr-allowances"),
    path(
        "hr/allowances/<uuid:pk>/",
        AllowanceAssignmentDetailView.as_view(),
        name="hr-allowance-detail",
    ),
    path("hr/leave-types/", LeaveTypeListCreateView.as_view(), name="hr-leave-types"),
    path("hr/leave-types/<uuid:pk>/", LeaveTypeDetailView.as_view(), name="hr-leave-type-detail"),
    path("hr/leaves/", EmployeeLeaveListCreateView.as_view(), name="hr-leaves"),
    path("hr/official-holidays/", OfficialHolidayListCreateView.as_view(), name="hr-official-holidays"),
    path(
        "hr/official-holidays/<uuid:pk>/",
        OfficialHolidayDetailView.as_view(),
        name="hr-official-holiday-detail",
    ),
    path("hr/attendance/", AttendanceListCreateView.as_view(), name="hr-attendance"),
    path("hr/attendance/import/", AttendanceImportView.as_view(), name="hr-attendance-import"),
    path("hr/commissions/report/", EmployeeCommissionReportView.as_view(), name="hr-commissions-report"),
    path("hr/commissions/", CommissionRecordListCreateView.as_view(), name="hr-commissions"),
    path("hr/payroll/sheet/", PayrollSheetView.as_view(), name="hr-payroll-sheet"),
    path("hr/payroll/statements/", PayrollStatementListCreateView.as_view(), name="hr-payroll-statements"),
    path(
        "hr/payroll/statements/<uuid:pk>/",
        PayrollStatementDetailView.as_view(),
        name="hr-payroll-statement-detail",
    ),
    path("hr/payment-types/", PaymentTypeListCreateView.as_view(), name="hr-payment-types"),
    path(
        "hr/payment-types/<uuid:pk>/",
        PaymentTypeDetailView.as_view(),
        name="hr-payment-type-detail",
    ),
    path("hr/payroll-payments/", PayrollPaymentListCreateView.as_view(), name="hr-payroll-payments"),
    path("hr/advances/", EmployeeAdvanceListCreateView.as_view(), name="hr-advances"),
    path("purchases/invoices/", PurchaseInvoiceListCreateView.as_view(), name="purchase-invoices"),
    path("purchases/returns/", PurchaseReturnListCreateView.as_view(), name="purchase-returns"),
    path("purchases/invoices/<uuid:pk>/", PurchaseInvoiceDetailView.as_view(), name="purchase-invoice-detail"),
    path(
        "purchases/invoices/<uuid:pk>/receive/",
        PurchaseInvoiceReceiveView.as_view(),
        name="purchase-invoice-receive",
    ),
    path(
        "purchases/invoices/<uuid:pk>/cancel/",
        PurchaseInvoiceCancelView.as_view(),
        name="purchase-invoice-cancel",
    ),
    path("purchases/products/", PurchaseProductsLookupView.as_view(), name="purchase-products"),
    path(
        "purchases/products/quick-create/",
        PurchaseQuickCreateProductView.as_view(),
        name="purchase-product-quick-create",
    ),
    path("inventory/reorder-alerts/", ReorderAlertsView.as_view(), name="reorder-alerts"),
    path(
        "purchases/orders/from-reorder/",
        CreateOrdersFromReorderView.as_view(),
        name="purchase-orders-from-reorder",
    ),
    path("purchases/orders/", PurchaseOrderListView.as_view(), name="purchase-orders"),
    path("purchases/orders/<uuid:pk>/", PurchaseOrderDetailView.as_view(), name="purchase-order-detail"),
    path(
        "purchases/orders/<uuid:pk>/receive/",
        PurchaseOrderReceiveView.as_view(),
        name="purchase-order-receive",
    ),
    path("pos/context/", PosContextView.as_view(), name="pos-context"),
    path("pos/products/", PosProductSearchView.as_view(), name="pos-products"),
    path("pos/sales/", PosSaleListCreateView.as_view(), name="pos-sales"),
    path("pos/exchanges/", PosExchangeView.as_view(), name="pos-exchanges"),
    path("pos/customers/review/", PosCustomerReviewListView.as_view(), name="pos-customers-review"),
    path(
        "pos/customers/<uuid:pk>/open-docs/",
        PosCustomerOpenDocsView.as_view(),
        name="pos-customer-open-docs",
    ),
    path("pos/sellers/", PosSellerListView.as_view(), name="pos-sellers"),
    path("pos/sellers/lookup/", PosSellerLookupView.as_view(), name="pos-sellers-lookup"),
    path("pos/delivery-orders/", PosDeliveryOrdersView.as_view(), name="pos-delivery-orders"),
    path(
        "pos/delivery-orders/<uuid:pk>/",
        PosDeliveryOrderDetailView.as_view(),
        name="pos-delivery-order-detail",
    ),
    path("sales/invoices/", SalesInvoiceListCreateView.as_view(), name="sales-invoices"),
    path("sales/invoices/<uuid:pk>/", SalesInvoiceDetailView.as_view(), name="sales-invoice-detail"),
    path("sales/returns/", SaleReturnListCreateView.as_view(), name="sales-returns"),
    path("sales/tax-invoices/", TaxInvoiceListView.as_view(), name="tax-invoices"),
    path("sales/quotations/", SalesQuotationListCreateView.as_view(), name="sales-quotations"),
    path("sales/quotations/lookup/", SalesQuotationLookupView.as_view(), name="sales-quotations-lookup"),
    path(
        "sales/quotations/<uuid:pk>/<str:action>/",
        SalesQuotationActionView.as_view(),
        name="sales-quotation-action",
    ),
    path("sales/reservations/", CustomerReservationListCreateView.as_view(), name="customer-reservations"),
    path("sales/reservations/lookup/", CustomerReservationLookupView.as_view(), name="customer-reservations-lookup"),
    path(
        "sales/reservations/<uuid:pk>/<str:action>/",
        CustomerReservationActionView.as_view(),
        name="customer-reservation-action",
    ),
    path("sales/seller-performance/", SellerPerformanceReportView.as_view(), name="seller-performance"),
    path("accounting/expense-types/", ExpenseTypeListCreateView.as_view(), name="expense-types"),
    path(
        "accounting/expense-types/next-code/",
        ExpenseTypeNextCodeView.as_view(),
        name="expense-types-next-code",
    ),
    path(
        "accounting/expense-types/<uuid:pk>/",
        ExpenseTypeDetailView.as_view(),
        name="expense-type-detail",
    ),
    path("accounting/gl-accounts/", GlAccountListView.as_view(), name="gl-accounts"),
    path("accounting/cost-centers/", CostCenterListView.as_view(), name="cost-centers"),
    path("accounting/treasuries/", TreasuryListView.as_view(), name="treasuries"),
    path("banking/banks/", BankListCreateView.as_view(), name="banks"),
    path("banking/banks/<uuid:pk>/", BankDetailView.as_view(), name="bank-detail"),
    path("banking/accounts/", BankAccountListCreateView.as_view(), name="bank-accounts"),
    path(
        "banking/accounts/<uuid:pk>/",
        BankAccountDetailView.as_view(),
        name="bank-account-detail",
    ),
    path(
        "banking/movements/",
        BankAccountMovementListCreateView.as_view(),
        name="bank-movements",
    ),
    path(
        "banking/movements/<uuid:pk>/post/",
        BankAccountMovementPostView.as_view(),
        name="bank-movement-post",
    ),
    path("banking/cheques/", ChequeListCreateView.as_view(), name="cheques"),
    path("banking/cheques/alerts/", ChequeAlertsView.as_view(), name="cheque-alerts"),
    path(
        "banking/payment-methods/dashboard/",
        PaymentMethodsDashboardView.as_view(),
        name="payment-methods-dashboard",
    ),
    path("banking/cheques/<uuid:pk>/", ChequeDetailView.as_view(), name="cheque-detail"),
    path(
        "banking/cheques/<uuid:pk>/pay/",
        ChequePayView.as_view(),
        name="cheque-pay",
    ),
    path(
        "banking/cheques/<uuid:pk>/reject/",
        ChequeRejectView.as_view(),
        name="cheque-reject",
    ),
    path(
        "banking/cheques/<uuid:pk>/deliver/",
        ChequeDeliverView.as_view(),
        name="cheque-deliver",
    ),
    path(
        "banking/cheques/<uuid:pk>/cancel/",
        ChequeCancelView.as_view(),
        name="cheque-cancel",
    ),
    path(
        "banking/cheques/<uuid:pk>/return/",
        ChequeReturnView.as_view(),
        name="cheque-return",
    ),
    path("banking/card-networks/", CardNetworkListCreateView.as_view(), name="card-networks"),
    path(
        "banking/card-networks/<uuid:pk>/",
        CardNetworkDetailView.as_view(),
        name="card-network-detail",
    ),
    path("banking/card-accounts/", CardAccountListCreateView.as_view(), name="card-accounts"),
    path(
        "banking/card-accounts/<uuid:pk>/",
        CardAccountDetailView.as_view(),
        name="card-account-detail",
    ),
    path(
        "banking/card-transactions/",
        CardTransactionListCreateView.as_view(),
        name="card-transactions",
    ),
    path(
        "banking/card-transactions/<uuid:pk>/settle/",
        CardTransactionSettleView.as_view(),
        name="card-transaction-settle",
    ),
    path(
        "banking/card-transactions/<uuid:pk>/reject/",
        CardTransactionRejectView.as_view(),
        name="card-transaction-reject",
    ),
    path(
        "banking/wallet-providers/",
        EWalletProviderListCreateView.as_view(),
        name="wallet-providers",
    ),
    path(
        "banking/wallet-providers/<uuid:pk>/",
        EWalletProviderDetailView.as_view(),
        name="wallet-provider-detail",
    ),
    path("banking/wallets/", EWalletAccountListCreateView.as_view(), name="e-wallets"),
    path(
        "banking/wallets/<uuid:pk>/",
        EWalletAccountDetailView.as_view(),
        name="e-wallet-detail",
    ),
    path(
        "banking/wallet-movements/",
        EWalletMovementListCreateView.as_view(),
        name="wallet-movements",
    ),
    path(
        "banking/wallet-movements/<uuid:pk>/post/",
        EWalletMovementPostView.as_view(),
        name="wallet-movement-post",
    ),
    path(
        "banking/channel-transfers/",
        ChannelTransferListCreateView.as_view(),
        name="channel-transfers",
    ),
    path("banking/statements/", BankingStatementView.as_view(), name="banking-statements"),
    path(
        "accounting/expense-vouchers/",
        ExpenseVoucherListCreateView.as_view(),
        name="expense-vouchers",
    ),
    path(
        "accounting/expense-vouchers/<uuid:pk>/",
        ExpenseVoucherDetailView.as_view(),
        name="expense-voucher-detail",
    ),
    path(
        "accounting/expense-vouchers/<uuid:pk>/<str:action>/",
        ExpenseVoucherActionView.as_view(),
        name="expense-voucher-action",
    ),
    path("accounting/cash-shifts/", CashShiftListView.as_view(), name="cash-shifts"),
    path("accounting/cash-shifts/open/", CashShiftOpenView.as_view(), name="cash-shift-open"),
    path("accounting/cash-shifts/my-open/", CashShiftMyOpenView.as_view(), name="cash-shift-my-open"),
    path("accounting/cash-shifts/active/", CashShiftActiveUsersView.as_view(), name="cash-shift-active"),
    path("accounting/cash-shifts/pos-gate/", CashShiftPosGateView.as_view(), name="cash-shift-pos-gate"),
    path(
        "accounting/enterprise-cash/",
        EnterpriseCashDashboardView.as_view(),
        name="enterprise-cash-dashboard",
    ),
    path(
        "accounting/cash-shifts/<uuid:pk>/daily-report/",
        CashShiftDailyReportView.as_view(),
        name="cash-shift-daily-report",
    ),
    path(
        "accounting/cash-shifts/<uuid:pk>/",
        CashShiftDetailView.as_view(),
        name="cash-shift-detail",
    ),
    path(
        "accounting/cash-shifts/<uuid:pk>/<str:action>/",
        CashShiftActionView.as_view(),
        name="cash-shift-action",
    ),
    path(
        "accounting/shift-handovers/",
        ShiftHandoverListCreateView.as_view(),
        name="shift-handovers",
    ),
    path(
        "accounting/shift-handovers/<uuid:pk>/",
        ShiftHandoverDetailView.as_view(),
        name="shift-handover-detail",
    ),
    path(
        "accounting/shift-handovers/<uuid:pk>/<str:action>/",
        ShiftHandoverActionView.as_view(),
        name="shift-handover-action",
    ),
    path(
        "accounting/treasury-balances/",
        TreasuryBalanceListView.as_view(),
        name="treasury-balances",
    ),
    path(
        "accounting/treasury-movements/",
        TreasuryMovementListCreateView.as_view(),
        name="treasury-movements",
    ),
    path(
        "accounting/treasury-movements/<uuid:pk>/<str:action>/",
        TreasuryMovementActionView.as_view(),
        name="treasury-movement-action",
    ),
    path(
        "accounting/treasury-audit/",
        TreasuryAuditLogView.as_view(),
        name="treasury-audit",
    ),
    path(
        "accounting/pending-shifts/",
        PendingShiftsView.as_view(),
        name="pending-shifts",
    ),
    path(
        "accounting/pending-shifts/<uuid:pk>/<str:action>/",
        PendingShiftActionView.as_view(),
        name="pending-shift-action",
    ),
    path(
        "accounting/chart-of-accounts/",
        ChartOfAccountsListCreateView.as_view(),
        name="chart-of-accounts",
    ),
    path(
        "accounting/chart-of-accounts/next-code/",
        ChartNextCodeView.as_view(),
        name="chart-next-code",
    ),
    path(
        "accounting/chart-of-accounts/lookup/",
        ChartGlAccountsLookupView.as_view(),
        name="chart-lookup",
    ),
    path(
        "accounting/chart-of-accounts/<uuid:pk>/",
        ChartOfAccountsDetailView.as_view(),
        name="chart-account-detail",
    ),
    path("accounting/currencies/", CurrencyListCreateView.as_view(), name="currencies"),
    path(
        "accounting/currencies/convert/",
        CurrencyConvertView.as_view(),
        name="currency-convert",
    ),
    path(
        "accounting/currencies/<uuid:pk>/",
        CurrencyDetailView.as_view(),
        name="currency-detail",
    ),
    path(
        "accounting/fixed-assets/",
        FixedAssetListCreateView.as_view(),
        name="fixed-assets",
    ),
    path(
        "accounting/fixed-assets/bulk-depreciate/",
        FixedAssetBulkDepreciateView.as_view(),
        name="fixed-assets-bulk-depreciate",
    ),
    path(
        "accounting/fixed-assets/<uuid:pk>/depreciate/",
        FixedAssetDepreciateView.as_view(),
        name="fixed-asset-depreciate",
    ),
    path(
        "accounting/journal-entries/",
        JournalEntryListCreateView.as_view(),
        name="journal-entries",
    ),
    path(
        "accounting/journal-entries/<uuid:pk>/",
        JournalEntryDetailView.as_view(),
        name="journal-entry-detail",
    ),
    path(
        "accounting/journal-entries/<uuid:pk>/<str:action>/",
        JournalEntryActionView.as_view(),
        name="journal-entry-action",
    ),
    path("accounting/reports/trial-balance/", TrialBalanceView.as_view(), name="trial-balance"),
    path("accounting/reports/balance-sheet/", BalanceSheetView.as_view(), name="balance-sheet"),
    path(
        "accounting/reports/income-statement/",
        IncomeStatementView.as_view(),
        name="income-statement",
    ),
    path("accounting/reports/general-ledger/", GeneralLedgerView.as_view(), name="general-ledger"),
    path("accounting/reports/export/", ReportExportView.as_view(), name="report-export"),
]
