# Generated by Django 5.2.14 on 2026-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="owner_initial_password",
            field=models.CharField(
                blank=True,
                help_text="كلمة المرور الأخيرة المعروفة — تُحفظ عند الإنشاء أو إعادة التعيين فقط",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="owner_username",
            field=models.CharField(
                blank=True,
                help_text="اسم مستخدم المالك في ERP (للمرجع من السوبر أدمن)",
                max_length=150,
            ),
        ),
    ]
