# Generated by Django 5.2.14 on 2026-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="branches/%Y/%m/"),
        ),
    ]
