# Generated by Django 5.2.14 on 2026-05-15 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_existing_users(apps, schema_editor):
    User = apps.get_model("erp", "User")
    from erp.permissions_schema import full_permissions

    perms = full_permissions()
    users = list(User.objects.order_by("created_at"))
    for index, user in enumerate(users, start=1):
        changed = []
        if not user.employee_code:
            user.employee_code = f"EMP-{index:03d}"
            changed.append("employee_code")
        if not user.permissions:
            user.permissions = perms
            changed.append("permissions")
        if index == 1 and not user.is_owner:
            user.is_owner = True
            changed.append("is_owner")
        if changed:
            user.save(update_fields=changed)


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0002_branch_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_created",
                to="erp.user",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_updated",
                to="erp.user",
            ),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments_created",
                        to="erp.user",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments_updated",
                        to="erp.user",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="erp.department",
            ),
        ),
        migrations.RunPython(backfill_existing_users, migrations.RunPython.noop),
    ]
