# Generated by Django 5.2.14 on 2026-05-18 15:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0009_inventory_extended"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "default_reorder_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="نسبة حد الطلب الافتراضية لكل الأصناف",
                        max_digits=6,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعدادات المخزون",
                "verbose_name_plural": "إعدادات المخزون",
            },
        ),
        migrations.AddField(
            model_name="season",
            name="barcode_next_number",
            field=models.PositiveIntegerField(
                default=100000, help_text="الرقم التالي للباركود التلقائي"
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="barcode_prefix",
            field=models.CharField(
                blank=True,
                help_text="بادئة الباركود للموسم (فارغ = كود الموسم)",
                max_length=20,
            ),
        ),
    ]
