# Generated by Django 5.2.14 on 2026-05-22 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_general_expense_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('expense_approval_limit', models.DecimalField(decimal_places=2, default=5000, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('approved', 'معتمدة')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_shifts_approved', to='erp.user')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to='erp.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_shifts_closed', to='erp.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to='erp.user')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneralExpenseVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('voucher_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('cheque', 'شيك')], default='cash', max_length=20)),
                ('beneficiary', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('posted', 'مرحّل'), ('cancelled', 'ملغى')], default='draft', max_length=20)),
                ('requires_manager_review', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_vouchers_approved', to='erp.user')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_vouchers', to='erp.branch')),
                ('cash_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_vouchers', to='erp.cashshift')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_vouchers', to='erp.costcenter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_vouchers_created', to='erp.user')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='erp.generalexpensetype')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_vouchers_posted', to='erp.user')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_vouchers_responsible', to='erp.user')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_expense_vouchers', to='erp.supplier')),
            ],
            options={
                'ordering': ['-voucher_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseVoucherAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='expense_vouchers/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='erp.generalexpensevoucher')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('void', 'ملغى')], default='draft', max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to='erp.user')),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generalexpensevoucher',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_voucher', to='erp.journalentry'),
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_order', models.PositiveSmallIntegerField(default=0)),
                ('memo', models.CharField(blank=True, max_length=300)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='erp.glaccount')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.journalentry')),
            ],
            options={
                'ordering': ['line_order'],
            },
        ),
        migrations.CreateModel(
            name='ShiftMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('sale', 'مبيعات'), ('return', 'مرتجعات'), ('expense', 'مصروفات'), ('collection', 'تحصيلات'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('opening', 'رصيد افتتاحي')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_movements', to='erp.generalexpensevoucher')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='erp.cashshift')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('cash', 'خزنة نقدية'), ('bank', 'بنك / تحويل')], default='cash', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasuries', to='erp.branch')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasuries', to='erp.glaccount')),
            ],
            options={
                'verbose_name': 'خزنة',
                'verbose_name_plural': 'الخزائن والبنوك',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='generalexpensevoucher',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_vouchers', to='erp.treasury'),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='treasury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to='erp.treasury'),
        ),
    ]
