# Generated by Django 5.2.14 on 2026-05-22 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_expense_vouchers_and_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='block_new_shift_if_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='handover_requires_review_on_diff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='stale_shift_hours',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='user_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=14),
        ),
        migrations.AddField(
            model_name='cashshift',
            name='handover_status',
            field=models.CharField(choices=[('none', 'بدون تسليم'), ('pending', 'بانتظار الاستلام'), ('completed', 'تم التسليم')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='kind',
            field=models.CharField(choices=[('cash', 'خزنة نقدية'), ('bank', 'بنك / تحويل'), ('e_wallet', 'محفظة إلكترونية')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('expected_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('received_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('difference_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_review', 'بانتظار المراجعة'), ('sender_signed', 'وقّع المسلّم'), ('received', 'استلم المستلم'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], default='draft', max_length=20)),
                ('requires_review', models.BooleanField(default=False)),
                ('mandatory_count_done', models.BooleanField(default=False)),
                ('sender_signed_at', models.DateTimeField(blank=True, null=True)),
                ('sender_signature', models.CharField(blank=True, max_length=64)),
                ('receiver_signed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_signature', models.CharField(blank=True, max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='erp.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_created', to='erp.user')),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_sent', to='erp.user')),
                ('from_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_out', to='erp.cashshift')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_reviewed', to='erp.user')),
                ('to_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_received', to='erp.user')),
                ('to_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_in', to='erp.cashshift')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='erp.treasury')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.UUIDField()),
                ('entity_code', models.CharField(blank=True, max_length=30)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_audit_logs', to='erp.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('movement_date', models.DateField()),
                ('movement_type', models.CharField(choices=[('receipt', 'قبض'), ('payment', 'صرف'), ('transfer', 'تحويل'), ('deposit', 'إيداع'), ('withdrawal', 'سحب')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_approval', 'بانتظار الاعتماد'), ('posted', 'مرحّل'), ('cancelled', 'ملغى')], default='draft', max_length=20)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_movements_approved', to='erp.user')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_movements', to='erp.branch')),
                ('cash_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_movements', to='erp.cashshift')),
                ('counter_treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counter_movements', to='erp.treasury')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_movements_created', to='erp.user')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='erp.treasury')),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
