# Generated by Django 5.2.14 on 2026-05-22 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_handover_treasury_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('rate_to_base', models.DecimalField(decimal_places=6, default=1, help_text='عدد وحدات العملة الأساس (EGP) لكل 1 من هذه العملة', max_digits=14)),
                ('is_base', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='glaccount',
            options={'ordering': ['tree_path', 'code'], 'verbose_name': 'حساب', 'verbose_name_plural': 'شجرة الحسابات'},
        ),
        migrations.AddField(
            model_name='glaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_accounts', to='erp.branch'),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='code_segment',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_accounts', to='erp.costcenter'),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='tree_path',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='account_type',
            field=models.CharField(choices=[('asset', 'أصول'), ('liability', 'التزامات'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], default='asset', max_length=20),
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('device', 'أجهزة'), ('vehicle', 'سيارات'), ('furniture', 'أثاث'), ('equipment', 'معدات')], default='device', max_length=20)),
                ('acquisition_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('useful_life_months', models.PositiveSmallIntegerField(default=36)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'قسط ثابت'), ('declining', 'متناقص')], default='straight_line', max_length=20)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, help_text='نسبة سنوية للمتناقص (مثلاً 25)', max_digits=6)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('fully_depreciated', 'مستهلك بالكامل'), ('disposed', 'مستبعد')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='erp.branch')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='erp.costcenter')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='erp.currency')),
                ('gl_accumulated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_as_accumulated', to='erp.glaccount')),
                ('gl_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_as_asset', to='erp.glaccount')),
                ('gl_expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_as_expense', to='erp.glaccount')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries_created', to='erp.user')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='erp.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='erp.fixedasset')),
            ],
            options={
                'ordering': ['-period', '-posted_at'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'period'), name='uniq_depreciation_per_period')],
            },
        ),
    ]
