# Generated by Django 5.2.14 on 2026-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_purchase_invoice_enhanced'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleline',
            name='saleline_variant_xor_composite',
        ),
        migrations.AlterField(
            model_name='stockadditionline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stockdisbursementline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
    ]
