# Generated by Django 5.2.14 on 2026-05-23 16:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_banking_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شبكة بطاقات',
                'verbose_name_plural': 'شبكات البطاقات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EWalletProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مزود محفظة',
                'verbose_name_plural': 'مزودو المحافظ',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('wallet', 'محفظة'), ('mixed', 'مختلط')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='CardMerchantAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(help_text='حساب البنك الذي تُسوّى عليه العمليات', on_delete=django.db.models.deletion.PROTECT, related_name='card_merchant_accounts', to='erp.bankaccount')),
                ('card_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_accounts', to='erp.cardnetwork')),
            ],
            options={
                'verbose_name': 'حساب فيزا / بطاقات',
                'verbose_name_plural': 'حسابات الفيزا',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('transaction_number', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('party_type', models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد'), ('other', 'أخرى')], default='other', max_length=20)),
                ('party_name', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'معلق (لم يُسوّى)'), ('settled', 'مُسوّى'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_transactions', to='erp.bankaccount')),
                ('card_merchant_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='erp.cardmerchantaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions_created', to='erp.user')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='erp.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='erp.sale')),
                ('settlement_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_settlements', to='erp.bankaccountmovement')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='erp.supplier')),
            ],
            options={
                'verbose_name': 'عملية بطاقة',
                'verbose_name_plural': 'عمليات البطاقات',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EWalletAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('wallet_number', models.CharField(blank=True, max_length=64)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, help_text='البنك المرتبط للتحويلات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_wallets', to='erp.bankaccount')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='erp.ewalletprovider')),
            ],
            options={
                'verbose_name': 'محفظة إلكترونية',
                'verbose_name_plural': 'المحافظ الإلكترونية',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ChannelTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transfer_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغى')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_transfers_created', to='erp.user')),
                ('from_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out_channel', to='erp.bankaccount')),
                ('to_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in_channel', to='erp.bankaccount')),
                ('from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out_channel', to='erp.ewalletaccount')),
                ('to_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in_channel', to='erp.ewalletaccount')),
            ],
            options={
                'verbose_name': 'تحويل بين قنوات الدفع',
                'verbose_name_plural': 'تحويلات قنوات الدفع',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EWalletMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('movement_type', models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر')], max_length=20)),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغى')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counter_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_movements', to='erp.ewalletaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_movements_created', to='erp.user')),
                ('e_wallet_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='erp.ewalletaccount')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_movements', to='erp.sale')),
            ],
            options={
                'verbose_name': 'حركة محفظة',
                'verbose_name_plural': 'حركات المحافظ',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
