# Generated by Django 5.2.14 on 2026-05-26 16:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_banking_cards_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_tax_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='qr_payload',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_registration_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('wallet', 'محفظة'), ('credit', 'آجل'), ('installment', 'تقسيط'), ('reserved', 'حجز'), ('mixed', 'مختلط')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('wallet', 'محفظة'), ('credit', 'آجل'), ('installment', 'تقسيط'), ('reserved', 'حجز'), ('mixed', 'مختلط')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='erp.sale')),
            ],
            options={
                'verbose_name': 'دفعة بيع',
                'verbose_name_plural': 'دفعات البيع',
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّلة'), ('cancelled', 'ملغاة')], default='posted', max_length=20)),
                ('refund_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك'), ('wallet', 'محفظة'), ('customer_account', 'حساب العميل')], default='cash', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='erp.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns_created', to='erp.user')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns', to='erp.customer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='erp.sale')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='erp.warehouse')),
            ],
            options={
                'verbose_name': 'مردود بيع',
                'verbose_name_plural': 'مردودات المبيعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('composite_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_return_lines', to='erp.compositeproduct')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='erp.saleline')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.salereturn')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_return_lines', to='erp.productvariant')),
            ],
            options={
                'verbose_name': 'بند مردود بيع',
                'verbose_name_plural': 'بنود مردودات البيع',
            },
        ),
    ]
