# Generated by Django 5.2.14 on 2026-05-26 16:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_sales_invoices_returns_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cashier_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
