# Generated by Django 5.2.14 on 2026-05-26 16:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0036_sale_commission_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('converted', 'تحول لفاتورة'), ('cancelled', 'ملغى')], default='active', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('deposit_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('wallet', 'محفظة'), ('credit', 'آجل'), ('installment', 'تقسيط'), ('reserved', 'حجز'), ('mixed', 'مختلط')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_reservations', to='erp.branch')),
                ('converted_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_reservations', to='erp.sale')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_reservations_created', to='erp.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='erp.customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_reservations', to='erp.warehouse')),
            ],
            options={
                'verbose_name': 'حجز عميل',
                'verbose_name_plural': 'حجوزات العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReservationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('composite_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_lines', to='erp.compositeproduct')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.customerreservation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_lines', to='erp.productvariant')),
            ],
            options={
                'verbose_name': 'بند حجز',
                'verbose_name_plural': 'بنود الحجوزات',
            },
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسل'), ('approved', 'موافق عليه'), ('converted', 'تحول لفاتورة'), ('cancelled', 'ملغى')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotations', to='erp.branch')),
                ('converted_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotations', to='erp.sale')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotations_created', to='erp.user')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotations', to='erp.customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotations', to='erp.warehouse')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('composite_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='erp.compositeproduct')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='erp.salesquotation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='erp.productvariant')),
            ],
            options={
                'verbose_name': 'بند عرض سعر',
                'verbose_name_plural': 'بنود عروض الأسعار',
            },
        ),
    ]
