# Generated by Django 5.2.14 on 2026-05-28 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_quotations_reservations_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentcontract',
            name='down_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='installmentcontract',
            name='financed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='installmentcontract',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='installmentcontract',
            name='penalty_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='installmentcontract',
            name='total_contract_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='installmentplantemplate',
            name='auto_add_interest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='installmentplantemplate',
            name='down_payment_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='installmentplantemplate',
            name='first_due_after_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='installmentplantemplate',
            name='interest_base',
            field=models.CharField(choices=[('before_down_payment', 'قبل المقدم'), ('after_down_payment', 'بعد المقدم')], default='after_down_payment', max_length=30),
        ),
        migrations.AddField(
            model_name='installmentplantemplate',
            name='interest_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='installmentplantemplate',
            name='interest_type',
            field=models.CharField(choices=[('percent', 'نسبة'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='installmentplantemplate',
            name='penalty_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
