# Generated by Django 5.2.14 on 2026-06-14 15:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0056_pos_exchange_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='okazionnoticeline',
            new_name='erp_okazion_notice__1b50ea_idx',
            old_name='erp_okazion_notice_product_idx',
        ),
        migrations.RenameIndex(
            model_name='storeoffernoticeline',
            new_name='erp_storeof_notice__11132f_idx',
            old_name='erp_store_offer_notice_prod_idx',
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='down_payment_refund',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مبلغ مقدم مُردود للعميل', max_digits=14),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='return_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='فوائد تقسيط مرتجعة', max_digits=14),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_also_customer',
            field=models.BooleanField(default=False, help_text='المورد يشتري منا أيضاً — يرتبط بحساب عميل'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('bank_account', 'حساب بنكي'), ('wallet', 'محفظة إلكترونية'), ('cheque', 'شيك'), ('promissory_note', 'كمبيالة'), ('other_papers', 'أوراق دفع أخرى')], default='cash', max_length=20),
        ),
    ]
